apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectcontrollers.getambassador.io
  labels:
    product: aes
    app.kubernetes.io/name: ambassador
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: ProjectController
    plural: projectcontrollers
    singular: projectcontroller
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v2
    served: true
    storage: true
