apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectrevisions.getambassador.io
  labels:
    product: aes
    app.kubernetes.io/name: ambassador
  annotations:
    "helm.sh/hook": crd-install
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.project.name
    name: Project
    type: string
  - JSONPath: .spec.ref
    name: Ref
    type: string
  - JSONPath: .spec.rev
    name: Rev
    type: string
  - JSONPath: .status.phase
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: ProjectRevision
    plural: projectrevisions
    singular: projectrevision
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v2
    served: true
    storage: true
