{{- if .Values.adminService.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ambassador.fullname" . }}-admin
  namespace: {{ include "ambassador.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    # Hard-coded label for Prometheus Operator ServiceMonitor
    service: ambassador-admin
    product: aes
  annotations:
    app.getambassador.io/owner: "Ambassador Labs"
    app.getambassador.io/repository: github.com/datawire/ambassador
    app.getambassador.io/description: "The Ambassador Edge Stack admin service for internal use and health checks."
    app.getambassador.io/documentation: https://www.getambassador.io/docs/latest/
    app.getambassador.io/chat: http://d6e.co/slack
    app.getambassador.io/bugs: https://github.com/datawire/ambassador/issues
    app.getambassador.io/support: https://www.getambassador.io/about-us/support/
    app.getambassador.io/dependencies: "None"
  {{- with .Values.adminService.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.adminService.type }}
  ports:
    - port: {{ .Values.adminService.port }}
      targetPort: admin
      protocol: TCP
      name: ambassador-admin
      {{- if (and (eq .Values.adminService.type "NodePort") (not (empty .Values.adminService.nodePort))) }}
      nodePort: {{ int .Values.adminService.nodePort }}
      {{- end }}
    - port: {{ .Values.adminService.snapshotPort }}
      targetPort: {{ .Values.adminService.snapshotPort }}
      protocol: TCP
      name: ambassador-snapshot
  selector:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if eq .Values.adminService.type "LoadBalancer" }}
  {{- if not (empty .Values.adminService.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.adminService.loadBalancerIP | quote }}
  {{- end }}
  {{- if not (empty .Values.adminService.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.adminService.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}
